### PR TITLE
Fix build with gcc8.3

### PR DESCRIPTION
**Pull request by peckato1**
sdbus::ObjectPath and sdbus::Signature copy constructors are implicitly
declared as deleted when compiling with Linaro's ARM toolchain [1] gcc8.3.
Explicitly listing the copy constructors for affected classes fixes the problem.

[1] https://www.linaro.org/

Here is the failure (for simplified code)
```cpp
const sdbus::ObjectPath foo("/path/to/somewhere");
const sdbus::ObjectPath bar(foo);
```
```  
/cesnet/build-clearfog/build/velia-custom/src/inputs/DbusSystemdInput.cpp: In member function ‘void velia::DbusSystemdInput::registerSystemdUnit(sdbus::IConnection&, const string&, const sdbus::ObjectPath&)’:
/cesnet/build-clearfog/build/velia-custom/src/inputs/DbusSystemdInput.cpp:77:36: error: use of deleted function ‘sdbus::ObjectPath::ObjectPath(const sdbus::ObjectPath&)’
     const sdbus::ObjectPath bar(foo);
                                    ^
In file included from /cesnet/build-clearfog/per-package/velia/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/sdbus-c++/ConvenienceApiClasses.inl:34,
                 from /cesnet/build-clearfog/per-package/velia/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/sdbus-c++/IObject.h:494,
                 from /cesnet/build-clearfog/per-package/velia/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/sdbus-c++/sdbus-c++.h:28,
                 from /cesnet/build-clearfog/build/velia-custom/src/inputs/DbusSystemdInput.h:10,
                 from /cesnet/build-clearfog/build/velia-custom/src/inputs/DbusSystemdInput.cpp:7:
/cesnet/build-clearfog/per-package/velia/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/sdbus-c++/Types.h:152:11: note: ‘sdbus::ObjectPath::ObjectPath(const sdbus::ObjectPath&)’ is implicitly declared as deleted because ‘sdbus::ObjectPath’ declares a move constructor or move assignment operator
     class ObjectPath : public std::string
           ^~~~~~~~~~
```

### CODE REVIEW

**Comment by sangelovic** [comment]
Thanks.
