### PR TITLE
chore: add atomic library dependency

### LINKED ISSUE #244: Missing atomic library during compilation on RPi (buster 32-bit)
(Maybe it's GCC issue, but leaving it here, for the record)

I'm using `sdbus-cpp` as a git submodule in my project. When I compiled it Raspberry Pi 4B (buster 32-bit, [official image January 28th 2022][1]) with `gcc8` as default,

```sh
$ gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
...
```

I got atomic library missing during linkage (e.g. [src/Connection.cpp#L390][0] likely),

```c
/usr/bin/ld: sdk-cpp/external/sdbus-cpp/libsdbus-c++.a(Connection.cpp.o): in function `sdbus::internal::Connection::notifyEventLoopNewTimeout() const':
Connection.cpp:(.text._ZNK5sdbus8internal10Connection25notifyEventLoopNewTimeoutEv+0x50): undefined reference to `__atomic_load_8'
/usr/bin/ld: sdk-cpp/external/sdbus-cpp/libsdbus-c++.a(Connection.cpp.o): in function `sdbus::internal::Connection::waitForNextRequest()':
Connection.cpp:(.text._ZN5sdbus8internal10Connection18waitForNextRequestEv+0x70): undefined reference to `__atomic_store_8'
```

which can be resolved by adding `atomic` library, then it compiles fine. I didn't analyze this more deeply.

```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -115,6 +115,7 @@ if(BUILD_LIBSYSTEMD)
 endif()
 target_link_libraries(sdbus-c++-objlib
         PUBLIC
+            atomic
             Systemd::Libsystemd
             Threads::Threads)
```

It compiles fine on my Ubuntu 20.04 PC after the change (so the change didn't break anything in this case).

```
$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```

[0]: https://github.com/Kistler-Group/sdbus-cpp/blob/master/src/Connection.cpp#L390
[1]: https://downloads.raspberrypi.org/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2022-01-28/2022-01-28-raspios-buster-armhf.zip

### PR DESCRIPTION
**Pull request by sangelovic**
Fixes #244

### CODE REVIEW

**Comment by sangelovic** [comment]
Closed in favor of a solution on the client side for this specific use case (see #244)
